### ISSUE TITLE
Many pages rendering as just "This discussion could not be loaded. Refresh the page and try again."

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#13]
Randomly (or at least, I haven't spotted a pattern) I am getting many pages that are just showing:
![image](https://user-images.githubusercontent.com/2512915/82342898-14e26600-99ea-11ea-8959-2954750b2659.png)
instead of any useful content.

**Comment by EugeneLoy** [comment]
Hi. Yes, I am aware of this. Will try to fix it sometime this week.
Meanwhile, if you have a lot of those you can try to add `-c 1` command line option. This should decrease chance of having this issue with cost of longer download time.

**Comment by JohnVeness** [comment]
Many thanks. The ``-c 1`` workaround has done the trick!

**Comment by EugeneLoy** [comment]
Fix for this has been pushed to master and will be included in `v1.7.0`
