### ISSUE TITLE
Unsightly grey bar at bottom of pages

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#14]
When rendering as pdf, all pages other than the last page seem to have a horizontal grey bar at the bottom. Most of the time this isn't a problem, but sometimes it interferes with the text. See the bar over "Now, let's start again":
![image](https://user-images.githubusercontent.com/2512915/82374428-f6469400-9a16-11ea-9652-577133c1436d.png)
It looks like some sort of page break indicator in the wrong place...

**Comment by EugeneLoy** [comment]
@JohnVeness What course\page is that? Circuits and Electronics from MIT?

**Comment by JohnVeness** [comment]
Yep, https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/course/ specifically https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/courseware/Week_1/Circuit_Analysis_Toolchest/?activate_block_id=block-v1%3AMITx%2B6.002.1x%2B2T2019%2Btype%40sequential%2Bblock%40Circuit_Analysis_Toolchest , But all pages seem to have that grey bar if the PDF, it's just that usually it doesn't happen to overlay any content.

**Comment by EugeneLoy** [comment]
Thanks, I'll check out what can be done here.

**Comment by JohnVeness** [comment]
For info, this doesn't happen when rendering to png, but pdf output is preferable to me (e.g. copy and search text).

**Comment by JohnVeness** [comment]
This might be a Chromium thing, as doing a print preview with Chromium I see the same grey bar at the bottom, going over text sometimes, but no grey bar in Firefox.

**Comment by EugeneLoy** [comment]
Fixed, pushed to master, will be released in `v1.7.0`
