### ISSUE TITLE
Hide "first-purchase-offer-banner" too

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#16]
I like how you tidy up the page. I suggest you also hide the "first-purchase-offer-banner" (or maybe all "offer-banner"s, assuming there are others), which looks like:
![image](https://user-images.githubusercontent.com/2512915/82456944-c053ef00-9aac-11ea-99ab-322ff1bace79.png)
Adding ``$(".first-purchase-offer-banner").hide();`` in the appropriate place in EdxDownloader.ts seems to do the trick.

**Comment by EugeneLoy** [comment]
Will add this. Thanks.

**Comment by EugeneLoy** [comment]
Added hiding this banner. This has been pushed to master and will be included in `v1.7.0`.
