### ISSUE TITLE
Some elements appear in PNGs but not PDFs

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#17]
Some MathJax objects were not being output in the PDF, although they are output if saving as PNG. For example, from course https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/course/ page https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/courseware/Week_1/Circuit_Analysis_Toolchest/15?activate_block_id=block-v1%3AMITx%2B6.002.1x%2B2T2019%2Btype%40vertical%2Bblock%40L2Node2 :

PNG:
![image](https://user-images.githubusercontent.com/2512915/82602553-2d4caf00-9ba9-11ea-94da-6cb5781ee359.png)

PDF:
![image](https://user-images.githubusercontent.com/2512915/82602501-1908b200-9ba9-11ea-8b4c-4d0bdba5e5cf.png)

I'm talking about the equation in the grey box between the answer and the submit button, if unclear.

**Comment by JohnVeness** [comment]
On a hunch, I tried 'screen' media type, following info in https://pptr.dev/#?product=Puppeteer&version=v3.1.0&show=api-pagepdfoptions which seems to fix.

Now PDF looks like:
![image](https://user-images.githubusercontent.com/2512915/82602768-7ef53980-9ba9-11ea-8fe3-246343115cd4.png)

Notice the annoying side effect that the margins are very small, which might be a problem if the PDF is printed. There are other side effects too, such as links being blue instead of black and underlined, and the (greyed-out) "Show Answer" buttons showing.

Anyway, specifically I added line ``saveTasks.push(page.emulateMediaType('screen'));`` before line ``saveTasks.push(page.pdf({ path: filename + '.pdf' }));``

**Comment by JohnVeness** [comment]
I've added 14mm margins to the generated PDF and it now looks pretty close layout to the original (print media rather than screen media) layout. See:
![image](https://user-images.githubusercontent.com/2512915/82613243-bd482400-9bbc-11ea-9f5e-c62742cf5b1f.png)
The relevant line is now ``saveTasks.push(page.pdf({ path: filename + '.pdf', margin: {top:'14mm', bottom:'14mm', left:'14mm', right:'14mm'}, format:'A4' }));``
Oh by the way, I added the format:A4 for my own preference, but this is separate from this issue.

**Comment by JohnVeness** [comment]
My first ever Github PR! I took out the A4 thing, as that should be separate.

**Comment by EugeneLoy** [comment]
@JohnVeness welcome :) There is a small issue with your PR though. Have a look at my review.

**Comment by JohnVeness** [comment]
You mean the Travis CI thing? I assumed that was because there was no $USER and $PASSWORD defined. Or have I missed something else?

**Comment by EugeneLoy** [comment]
> You mean the Travis CI thing?
No, you can ignore that.
> Or have I missed something else?
No. I forgot to publish review. Just did it, check it out.
