### ISSUE TITLE
"Show answer" buttons appear not to be pressed

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#19]
I originally mentioned this in issue #6 (https://github.com/EugeneLoy/edx-archive/issues/6#issuecomment-631760900_) but it deserves a new issue:

The intended feature of the "Show Answer" button being clicked before the page is saved to PNG or PDF isn't working for me. I see the code to click the button (``$(".show").trigger("click")``) in ``prettifyPage()``, but I think what is happening is that sometimes it takes a few seconds for the answers to load (especially on some pages where that button not only shows the answer, but a long explanation with images etc, e.g. page https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/courseware/Week_1/Circuit_Analysis_Toolchest/?activate_block_id=block-v1%3AMITx%2B6.002.1x%2B2T2019%2Btype%40sequential%2Bblock%40Circuit_Analysis_Toolchest in course https://courses.edx.org/courses/course-v1:MITx+6.002.1x+2T2019/course/) and the code isn't waiting long enough before taking a screenshot or printing to PDF.

Moving the line ``await page.waitFor(this.configuration.delay * 1000);`` down from its current position to between ``await page.evaluate(prettifyPage);`` and ``await this.savePage(baseName, page);`` seems to fix this, but only if I also increase the delay, e.g. ``-d 5``.

This works but seems rather inefficient, and still could miss some especially slow-to-load answers. I don't know if there's a way you can programmatically check whether the browser has completely finished loading all the answers before saving..?

**Comment by JohnVeness** [comment]
Haha I notice you've just reworked that part of the code in https://github.com/EugeneLoy/edx-archive/commit/01b353e4bd3ab7e77c72dac990a574e7c8f4aff4 - I should have checked first!

**Comment by EugeneLoy** [comment]
@JohnVeness Yep :)
