### ISSUE TITLE
Allow user to pick other paper formats for PDF

### ISSUE THREAD

**Issue by JohnVeness** [EugeneLoy/edx-archive#21]
At the moment, edx-archive outputs Letter-size PDFs, which is the default from puppeteer. It would be useful to allow the user to choose their own paper format. https://pptr.dev/#?product=Puppeteer&version=v3.1.0&show=api-pagepdfoptions gives all the options, although I expect most people would only require the actual "format" option (e.g. A4) and maybe a choice of landscape/portrait.

**Comment by EugeneLoy** [comment]
I think hardcoding format to `A4` will be good enough. I feel like most of the users won't print these pdfs and those who do will print to `A4` in 99% of the cases.

Having that said, if I hear from people who need this - I am ok with implementing it.

@JohnVeness let me know if you want to contribute PR for this.

**Comment by JohnVeness** [comment]
A4 would suit me, but I wouldn't want to speak for others.

I'll submit a PR hardcoding A4 anyway.
