### ISSUE TITLE
Nothing downloaded

### ISSUE THREAD

**Issue by carlosmag** [EugeneLoy/edx-archive#30]
Hi,

I've tested v1.8.2 with this [course](https://courses.edx.org/courses/course-v1:HarvardX+SW12.1+1T2019a/course/) and nothing was downloaded.
Maybe I am missing something?

Thanks

**Comment by EugeneLoy** [comment]
Hi. Thanks for reporting this. Fix for this is released as `1.8.3`.

**Comment by carlosmag** [comment]
Hi!
It seems to be working well now!

Thanks for the fix!
