### ISSUE TITLE
Pngs not downloading

### ISSUE THREAD

**Issue by asdviom** [EugeneLoy/edx-archive#5]
my command prompts says done but nothing actually downloads

**Comment by EugeneLoy** [comment]
@asdviom Hi. Could you tell me what course are you trying to download?

**Comment by asdviom** [comment]
TokyoTechX: EE101Jx
Introduction to Electrical and Electronic Engineering
https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/course/

**Comment by asdviom** [comment]
well im glad it works! and where is the archive directory located?

**Comment by asdviom** [comment]
im using the default directory i dont know where its located

**Comment by EugeneLoy** [comment]
> where is the archive directory located?

current directory, i.e. the directory where you are running `edx-archive`.

**Comment by asdviom** [comment]
i downloaded the edx archive and i have it in a folder on my desktop

**Comment by asdviom** [comment]
and im using cmd to run

**Comment by EugeneLoy** [comment]
Ok. Can you copy-paste what you have in your cmd here?

**Comment by asdviom** [comment]
yes one sec

**Comment by EugeneLoy** [comment]
Starting from the point where you run it, and finishing with "Done" message. Also, don't forget to add `--debug` switch.

**Comment by asdviom** [comment]
ok where do i add the --debug switch? after it says done or before?

**Comment by asdviom** [comment]
C:\Users\hiras>edx-archive -u hirasseru@outlook.com -p Russell45567 --format png https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/course/
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@e005e9f4f0494c94b70b77e587944a7c.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@22c060b2e2754873b3b9853db8884a71.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@6b09b22be617448a9f3a61efc44de16b.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@a8272cf0b77f46fd84275802eb5dbcc1.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@381fca45c5b04cdca60c84a2075b5e15.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@d4ccaae043e94eb8906d8b7cde3adfb8.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@eb82829dadf14fbcb0cbe3409b7e20e6.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@f20962ac28bb4c20a0a0a09cd585031a.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@4ce31a31c5254ff0b6cae305294fc0e8.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@3dbcb088b7f645abbefe905239889872.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@27c55fb17e414cdabf761672c360eee8.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@deb5ac95ff2343fc9dcdae3dcecd0c47.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@f964c56e107745778fcfa5baaaa83b17.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@9bb0ad309201482a89d67430cb2d7f36.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@625f8eb6a9a646eb816ab8efe8115fb1.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@6c1a94a9fced4916b37efc2fe7afd917.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@3318aba7f51a4da093b6209bce78983f.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@5ec35ca64f844ca780f447568a163c34.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@92aa2eb110ae4d98973b4ca1860e7b6d.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@7f4fd96b136d4292b2a7b81785a7c286.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@d8b98f7876844eb2b6a197ae7f4c4c78.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@fc0412693c834aca87151e980b0ac651.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@aeecccfe5cb84e8ab4f4300c4aabb506.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@835468482f7941b2859054dd3b9ce17d.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@5d68946d3bc44281a2b0d3a0f9ffc45f.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@d6bef8376fcb4bbf868456788b59218e.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@2bee32e04a634c6e846d8ad114051cfd.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@bafde40b64274cd9b87c7c73dffb74fc.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@073de962ed624d10a0b4c7c9cb5039ab.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@36f9fc8f74d248dd9bcd4d94ee330f48.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@26cc40de35884a55a0c5e1e85a38597c.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@99631df4b83546f3a326180dc6778a33.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@7421c8fea26344e48faa69fe9143eed2.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@4f3f0cb20e8a4addb6d29b57e3578b4f.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@bc16a3a92d8a48aea732c517772213c3.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@932469b5c9df4ebd8145e56062d1c587.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@9cc342c66c204f72a9882cd0e75dd417.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@352e0e99cd494f20a43b3d4e923e8d7f.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@16567dd78fa64f21b8fea248fd8c769a.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@7b6e405149f1446e85102958264faaf4.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@c496755d55624bed9d3e381a933ecab5.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@3541cfaafaa245f59249464d560f564d.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@c62266e783a547bfb4861482a8c5daf2.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@da697d384fb149a999240230ad2e485b.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@65121ad940f545c8925f3d803152fdf7.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@ea2c2dfdb2fe457f9f89dee5e5ee2c77.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@8562db02d29e4a0396b945bd424096b7.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@062ddde5e9f1493d9190953bd1747198.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@43ff0d58cc564e158311de1ef685f426.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@4cbbb9871ed342b98584ffb0a6aa310c.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@21189b388e4742a2b251ba92258a1fbe.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@90b8b9620f4544ee991fed0d7cb27b34.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@f4c4e2a174e14c13ac83a6ade5f46c6d.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@239db054b9fd4fe085a7da84cbf8ed32.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@60472630adcc4f1885b5833bd10be94c.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@0971daae77fb4d92a669a1852a40684e.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@1d85fd18d9df4727987860d090e0641f.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@4f17c790512c497f84149884def52e3b.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@0e27c357fb0341058ca77457d0c0edde.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@36228a5b1a884d64aef0ef5907072d6d.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@bce13362b20645d5b8f2546b4f8b217b.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@4979337d45264e1384468b92aa4caf92.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@72d52329a9684e9d8135aa2147054a42.
Processing page: https://courses.edx.org/courses/course-v1:TokyoTechX+EE101Jx+3T2017/jump_to/block-v1:TokyoTechX+EE101Jx+3T2017+type@vertical+block@07357d81282e4e6fa892f260786991b1.
Done.

**Comment by asdviom** [comment]
heres what is says.

**Comment by EugeneLoy** [comment]
Ok. Does folder "C:\Users\hiras\Archive" exist? Is it empty?

**Comment by asdviom** [comment]
yes i found it and everything is there!

**Comment by asdviom** [comment]
wow thankyou so much!

**Comment by asdviom** [comment]
so does this give you the answers?

**Comment by EugeneLoy** [comment]
Great. In the next release I'll make it more obvious where pages are saved.
