### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by zara-ps** [EugeneLoy/edx-archive#9]
hey there 
 so I get this error (TimeoutError: Navigation timeout of 30000 ms exceeded)even when I try to download the demo course and I tried multiple times with different courses but it's the same error every time
 sorry since a beginner i'm probably doing smth wrong -___-
by the way thank you so much!

**Comment by EugeneLoy** [comment]
Hi.

I just checked it I am able to download demo course. It looks like you have poor connection with Edx.

Here is the list of things you can try out:

1. Decrease number of concurrent downloads to 1 by adding `-c 1` switch.
2. Increase number of download retries with `-r <number>` (default is 3)

Using all of the above will slow down overall download speed but increase reliability.

Let me know if this helps.

**Comment by zara-ps** [comment]
yes it works perfectly ,thank you soo much for answering! 
this tool is very useful thanks a lot for creating it
